Repository FShimaneMentees/Stidbit, pull requests merged in 2018-03, with the labels that each got.

#31 add: ユーザー新規登録処理の実装
  app/assets/javascripts/users.coffee
  app/assets/stylesheets/users.scss
  app/controllers/users_controller.rb
  app/helpers/users_helper.rb
  app/models/user.rb
  app/views/users/new.html.erb
  config/locales/ja.yml
  config/routes.rb
  test/controllers/users_controller_test.rb
Labels: レビューしてくれぇ

#33 add: ログイン・ログアウト機能作成
  app/assets/javascripts/sessions.coffee
  app/assets/stylesheets/sessions.scss
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/tidbits_controller.rb
  app/controllers/users_controller.rb
  app/helpers/sessions_helper.rb
  app/views/layouts/application.html.erb
  app/views/sessions/login_form.html.erb
  config/routes.rb
  test/controllers/sessions_controller_test.rb
Labels: tidbit, ユーザー

#34 add: いいね機能の追加
  app/assets/images/icon_heart.png
  app/assets/images/icon_red_heart.png
  app/assets/stylesheets/like.css
  app/controllers/likes_controller.rb
  app/models/like.rb
  app/models/tidbit.rb
  app/views/likes/_like.html.erb
  app/views/likes/create.js.erb
  app/views/likes/destroy.js.erb
  app/views/tidbits/index.html.erb
  app/views/tidbits/show.html.erb
  config/routes.rb
  db/migrate/20180303030434_create_likes.rb
  db/migrate/20180303074847_add_likes_count_to_tidbits.rb
  test/fixtures/likes.yml
  test/models/like_test.rb
Labels: レビューしてくれぇ

#36 add: editorconfig の追加
  .editorconfig
  db/schema.rb
Labels: 開発環境改善

#40 modify: likes_countカラムの初期値を設定
  db/migrate/20180303074847_add_likes_count_to_tidbits.rb
  db/schema.rb
Labels: レビューしてくれぇ

#41 add: rspecGemの追加
  .rspec
  Gemfile
  Gemfile.lock
  config/application.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: レビューしてくれぇ

#43 add: マイページ
  app/controllers/tidbits_controller.rb
  app/controllers/users_controller.rb
  app/models/tidbit.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  app/views/tidbits/index.html.erb
  app/views/tidbits/show.html.erb
  app/views/users/my_page.html.erb
  config/routes.rb
  db/migrate/20180312013229_add_user_id_to_tidbits.rb
  db/schema.rb
  docker-compose.yml
Labels: レビューしてくれぇ

#44 add: コメント機能の追加
  app/controllers/comments_controller.rb
  app/controllers/tidbits_controller.rb
  app/models/comment.rb
  app/models/tidbit.rb
  app/models/user.rb
  app/views/tidbits/show.html.erb
  config/locales/ja.yml
  config/routes.rb
  db/migrate/20180326100505_create_comments.rb
  db/schema.rb
  spec/factories/comments.rb
  spec/models/comment_spec.rb
Labels: レビューしてくれぇ
