Repository FShimaneMentees/Stidbit, pull requests merged in 2018-02, with the labels that each got.

#14 modify: db 設定は git 管理対象外にする
  .gitignore
Labels: その他

#20 add: 新規投稿処理の作成
  app/controllers/tidbits_controller.rb
  app/views/tidbits/new.html.erb
  config/routes.rb
Labels: レビューしてくれぇ

#19 add: User モデル作成
  app/models/user.rb
  db/migrate/20180217032157_create_users.rb
  db/schema.rb
  test/fixtures/users.yml
  test/models/user_test.rb
Labels: レビューしてくれぇ

#23 add: 豆記事投稿バリデーション処理の実装
  Gemfile
  Gemfile.lock
  app/controllers/tidbits_controller.rb
  app/models/tidbit.rb
  app/views/layouts/application.html.erb
  app/views/tidbits/new.html.erb
  config/application.rb
  config/locales/ja.yml
Labels: tidbit, レビューしてくれぇ

#22 add: 詳細閲覧機能追加
  app/controllers/tidbits_controller.rb
  app/views/tidbits/index.html.erb
  app/views/tidbits/show.html.erb
  config/routes.rb
Labels: tidbit

#24 add: rubocop導入
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/models/tidbit.rb
Labels: 開発環境改善
